// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import domain "server/domain"
import mock "github.com/stretchr/testify/mock"

// AuthGuard is an autogenerated mock type for the AuthGuard type
type AuthGuard struct {
	mock.Mock
}

// IsAuthorized provides a mock function with given fields: login, role
func (_m *AuthGuard) IsAuthorized(login string, role domain.UserRole) bool {
	ret := _m.Called(login, role)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, domain.UserRole) bool); ok {
		r0 = rf(login, role)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// IsLoggedIn provides a mock function with given fields: login
func (_m *AuthGuard) IsLoggedIn(login string) bool {
	ret := _m.Called(login)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
